docs_dir: .

# Project information
site_name: satcube
site_url: https://csaybar.github.io/satcube
site_author: Cesar Aybar
site_description: Satcube is a Python package for managing Sentinel-2 satellite data cubes.

# Repository
repo_url: https://github.com/csaybar/satcube
repo_name: satcube
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satcube.png
  favicon: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satcube.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide 

# Page tree
nav:
  - Home: 
    - README.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md
    - Code of conduct: CODE_OF_CONDUCT.md
    
# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.copybutton
  - pymdownx.arithmatex
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist


# Extra CSS
extra_css:
  - docs/style/style.css

# Extra JavaScript
extra_javascript:
  - docs/js/copybutton.js
